apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyndns-noip
  labels:
    app: dyndns-noip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyndns-noip
  template:
    metadata:
      labels:
        app: dyndns-noip
    spec:
      containers:
        - name: updater
          image: theadzik/dyndns-noip:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dyndns-noip-secret
          volumeMounts:
            - mountPath: /history
              name: history
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 10002
        runAsGroup: 20002
      volumes:
        - name: history
          emptyDir: {}
